# Generated by Django 2.0.6 on 2018-06-19 03:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=12)),
                ('avatar', models.ImageField(blank='True', default='pic_folder/None/user.png', upload_to='pic_folder/')),
                ('reputacion', models.PositiveIntegerField(null=True)),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('fechadenacimiento', models.DateField(default=datetime.date.today, verbose_name='cumpleaños')),
                ('direccion', models.CharField(blank=True, max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=16)),
                ('sexo', models.CharField(blank=True, choices=[('F', 'Femenino'), ('M', 'Masculino')], max_length=2)),
                ('status', models.BooleanField(default=True)),
                ('seguidores', models.ManyToManyField(blank=True, to='users.Usuario')),
            ],
        ),
    ]
